global:
  helmValues:
    - name: stage
      value: $STAGE
    - name: dns.host
      value: "admin.dev-workshop-holger.iits.tech"
argocd-config:
  namespace: argocd
cert-manager:
  namespace: cert-manager
traefik:
  namespace: routing
  helmValues:
    - name: "traefik.deployment.replicas"
      value: "3"
storage-classes:
  namespace: storage
admin-dashboard:
  namespace: admin
kafka:
  namespace: kafka
basic-auth-gateway:
  namespace: routing